### ISSUE TITLE
[Device-Manager] Problem with the endpoint '/device' with method POST when using verbose parameter

### ISSUE THREAD

**Issue by raulnegreiros** [dojot/dojot#992] opened 2019-03-20 19:01 UTC
When the user tries to create a new device with the parameter `verbose` active the server always answers `internal error`, but the device is created.

Request:
```sh
curl -X POST http://localhost:8000/device?verbose=true -H "Authorization: Bearer ${JWT}" -H 'Content-Type:application/json' -d ' {
  "templates": [
    "19"
  ],
  "label": "dummy_dev"
}'
```

Response:
```sh
{
  "msg": "Internal Error"
}
```

**Comment by giovannicuriel** [comment] 2019-04-16 18:41
Duplicate of #1080

**Closed by giovannicuriel** 2019-04-16 18:41 UTC
Labels: Team:Backend, Type:Bug
