### ISSUE TITLE
Import/Export: Import fails if data already exists

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#1480] opened 2020-06-03 18:46 UTC
**Steps to reproduce the problem:**

1. Create templates, devices and flows
2. Export the data
3. Restart the dojot
4. Import the data that was exported
5. Re-import the same data or import new data / empty data

- 1st import is successful

data-manager log:
```
<17:44:30 03/06/2020> -- DEBUG: Will import data.
<17:44:30 03/06/2020> -- DEBUG: Will call delete http://flowbroker:80/v1/flow
<17:44:30 03/06/2020> -- DEBUG: Flows deleted.
<17:44:30 03/06/2020> -- DEBUG: Will call delete http://flowbroker:80/v1/node
<17:44:30 03/06/2020> -- DEBUG: Nodes deleted.
<17:44:30 03/06/2020> -- DEBUG: Nodes imported.
<17:44:30 03/06/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
<17:44:30 03/06/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
<17:44:30 03/06/2020> -- DEBUG: Flows imported.
<17:44:30 03/06/2020> -- DEBUG: Will call http://device-manager:5000/import
<17:44:30 03/06/2020> -- DEBUG: Devices and templates imported.
<17:44:30 03/06/2020> -- DEBUG: Will call delete http://cron:5000/cron/v1/jobs
<17:44:30 03/06/2020> -- DEBUG: Cron jobs deleted
<17:44:30 03/06/2020> -- DEBUG: Cron jobs imported
```
device-manager log:
```
[03/06/20 - 17:44:30] |ImportHandler| INFO:  Starting importing data...
[03/06/20 - 17:44:30] |ImportHandler| INFO:  Removed sequences
[03/06/20 - 17:44:30] |ImportHandler| INFO:  Deleted overrides
[03/06/20 - 17:44:30] |ImportHandler| INFO:  Deleted devices
[03/06/20 - 17:44:30] |ImportHandler| INFO:  Deleted templates
[03/06/20 - 17:44:30] |ImportHandler| INFO:  Saved templates
[03/06/20 - 17:44:30] |ImportHandler| INFO:  Saved devices
[03/06/20 - 17:44:30] |ImportHandler| INFO:  Restored sequences
[03/06/20 - 17:44:30] |BackendHandler| INFO:  Publishing create event to Kafka
[03/06/20 - 17:44:30] |BackendHandler| INFO:  Publishing create event to Kafka
[03/06/20 - 17:44:30] |BackendHandler| INFO:  Publishing create event to Kafka
[03/06/20 - 17:44:30] |ImportHandler| INFO:  Imported data!
```

- **the 2nd import fails**

data-manager log:
```
<17:45:06 03/06/2020> -- DEBUG: Will import data.
<17:45:06 03/06/2020> -- DEBUG: Will call delete http://flowbroker:80/v1/flow
<17:45:06 03/06/2020> -- DEBUG: Flows deleted.
<17:45:06 03/06/2020> -- DEBUG: Will call delete http://flowbroker:80/v1/node
<17:45:06 03/06/2020> -- DEBUG: Nodes deleted.
<17:45:06 03/06/2020> -- DEBUG: Nodes imported.
<17:45:06 03/06/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
<17:45:06 03/06/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
<17:45:06 03/06/2020> -- DEBUG: Flows imported.
<17:45:06 03/06/2020> -- DEBUG: Will call http://device-manager:5000/import
<17:45:06 03/06/2020> -- DEBUG: Received error on import data, Error: Request failed with status code 400. Rejecting the request
```
device-manager log:
```
[03/06/20 - 17:45:06] |ImportHandler| INFO:  Starting importing data...
[03/06/20 - 17:45:06] |ImportHandler| INFO:  Removed sequences
[03/06/20 - 17:45:06] |ImportHandler| INFO:  Deleted overrides
[03/06/20 - 17:45:06] |ImportHandler| ERROR:  notifies_deletion_to_kafka() missing 1 required positional argument: 'tenant'
[03/06/20 - 17:45:06] |ImportHandler| ERROR:  Failed to import data
```

![image](https://user-images.githubusercontent.com/37310063/83672997-8eaf4d80-a5ad-11ea-9fed-c067514a12b1.png)

Affected version: **v0.5.0-alpha.1**

**Comment by bizetti** [comment] 2020-06-05 13:49
Ticket analysis meeting (June, 5th): It has to be fixed.

**Comment by luissajunior** [comment] 2020-07-14 12:45
Cant reproduce the bug. Maight be resolved with by issue?

**Comment by betefaber** [comment] 2020-08-04 14:17
The bug has not been resolved. The error only happens if data already exists.

![1480](https://user-images.githubusercontent.com/37310063/89304202-8b831d00-d643-11ea-8cae-65019855303b.png)

```
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will import data.
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call delete http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Flows deleted.
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call delete http://flowbroker:80/v1/node
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Nodes deleted.
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Nodes imported.
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://flowbroker:80/v1/flow
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Flows imported.
data-manager-7b986f99d8-8wq8m data-manager <14:08:56 04/08/2020> -- DEBUG: Will call http://device-manager:5000/import
data-manager-7b986f99d8-8wq8m data-manager <14:08:57 04/08/2020> -- DEBUG: Received error on import data, Error: Request failed with status code 400. Rejecting the request
```

Tested in **v0.5.0-alpha.3**

![image](https://user-images.githubusercontent.com/37310063/89304633-09472880-d644-11ea-9cac-3155b3fe854e.png)

**Comment by FrancielePessi** [comment] 2020-10-28 03:49
Environment with existing data
![Captura de tela de 2020-10-28 00-47-19.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/2300b0e0-cf73-48b5-8a9d-1ed05fca1245)

Importing data
![Captura de tela de 2020-10-28 00-47-36.png](https://images.zenhubusercontent.com/5d138e07f0489e0b0b4be7a3/8e64aa6b-4b88-451b-ac26-9031f2eadcdd)


Version tested: 0.5.0 rc1

**Closed** 2020-10-30 11:34 UTC
Labels: Priority:High, Status:Rejected, Team:Backend, Type:Bug :bug:
