### ISSUE TITLE
Failed to access actuate attribute chart from device

### ISSUE THREAD

**Issue by pedropaulomartucci** [dojot/dojot#507] opened 2018-06-04 16:47 UTC
Create a template with actuator attributes using the REST API:
```
{
  "attrs": [
    {
      "type": "actuator",
      "value_type": "boolean",
      "metadata": [
        {
          "type": "lwm2m",
          "static_value": "/3311/0/5850",
          "value_type": "string",
          "label": "path"
        }
      ],
      "label": "LightControl-On_Off-0"
    },
    {
      "type": "actuator",
      "value_type": "integer",
      "metadata": [
        {
          "type": "lwm2m",
          "static_value": "/3311/0/5851",
          "value_type": "string",
          "label": "path"
        }
      ],
      "label": "LightControl-Dimmer-0"
    }
  ],
  "label": "Light Control"
}
```

When creating devices and accessing their dashboard it's impossible to open the actuator attribute chart. Once the actuator attributes are read/write it should have worked.

We also noted that listing the template attributes wasn't working properly.
![image](https://user-images.githubusercontent.com/9469719/40930294-a40bac86-67fd-11e8-86c5-70e49515c37d.png)

**Comment by giovannicuriel** [comment] 2018-06-04 16:49
This is related to dojot/gui#195 and dojot/gui#197.

**Comment by pedropaulomartucci** [comment] 2018-06-04 18:41
Tested again with latest version: `0.3.0-nightly20180604`

The device dashboard now list the actuator attributes but it still not allow plotting their charts. I'm not sure if actuator attributes was designed to not be readable or something like that. Thinking about LwM2M they  are read/write and may be plotted like dynamic attributes.

![image](https://user-images.githubusercontent.com/9469719/40935156-95e71428-680d-11e8-9fd2-fd4bcfb99373.png)

Listing template attributes works with boolean but still not works with integer `LightControl-Dimmer-0`
![image](https://user-images.githubusercontent.com/9469719/40934837-79a0695a-680c-11e8-86c0-a900990d9631.png)

**Comment by fernandoMessias** [comment] 2018-06-19 13:52
Maybe the problem is in backend. The actuator comes as a configuration attribute and not a data attribute. I think that is better treat this in backend instead of treat in GUI (for each attribute, verify if is an actuator and put as a data attribute...).

**Comment by rascaraficci** [comment] 2021-06-21 19:20
It was fixed in the newer versions.

**Closed by rascaraficci** 2021-06-21 19:20 UTC
Labels: Status:Analysed
