### ISSUE TITLE
[GUI] Device details: adjust the size of the device id field

### ISSUE THREAD

**Issue by betefaber** [dojot/dojot#458] opened 2018-04-25 19:34 UTC
![image](https://user-images.githubusercontent.com/37310063/39268442-62ba88c2-48a6-11e8-8a1f-2965e5417f9b.png)

**Comment by fernandoMessias** [comment] 2018-04-25 19:36
This PR https://github.com/dojot/gui/pull/155 fix this.

**Comment by cfrancisco** [comment] 2018-04-27 03:48
I couldn't reproduce it. @fernandoMessias, can you check it?

**Comment by fernandoMessias** [comment] 2018-06-19 16:30
This problem was solved, I will close this issue.

**Closed by fernandoMessias** 2018-06-19 16:30 UTC
Labels: Priority:Low, Team:Frontend, Type:Bug, Type:Enhancement
